site_name: COMPAS Brep
site_url: https://GKR.github.io/compas_brep/

repo_name: GKR/compas_brep
repo_url: https://github.com/GKR/compas_brep/

copyright: Copyright &copy; 2024 - 2026, ETH Zurich - Gramazio Kohler Research

extra:
  homepage: https://GKR.github.io/compas_brep/

theme:
  name: material
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/images/compas_logo_white_transparent.png
  favicon: assets/images/compas_favicon.png
  features:
    - content.code.copy
    - content.footnote.tooltips
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.follow

extra_css:
  - assets/css/custom.css

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - footnotes
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - toc:
      permalink: "¤"

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          inventories:
            - https://docs.python.org/3/objects.inv
            - https://compas.dev/compas/latest/objects.inv
          options:
            allow_inspection: true
            backlinks: tree
            docstring_options:
              ignore_init_summary: true
              trim_doctest_flags: true
            docstring_style: numpy
            docstring_section_style: list
            filters: public
            group_by_category: true
            heading_level: 1
            inherited_members: false
            line_length: 88
            merge_init_into_class: true
            modernize_annotations: true
            parameter_headings: false
            preload_modules: [mkdocstrings, compas]
            relative_crossrefs: true
            scoped_crossrefs: true
            separate_signature: true
            show_bases: false
            show_category_heading: true
            show_docstring_attributes: true
            show_docstring_functions: true
            show_docstring_modules: false
            show_if_no_docstring: false
            show_inheritance_diagram: false
            show_root_heading: true
            show_root_full_path: true
            show_signature: true
            show_signature_annotations: true
            show_signature_type_parameters: true
            show_source: false
            show_submodules: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary:
              modules: false
            unwrap_annotated: true

nav:
  - Home: index.md
  - Get Started:
      - Introduction: introduction.md
      - Installation: installation.md
      - Examples: examples.md
  - API Reference:
      - compas_brep: reference/compas_brep.md
      - Topology:
          - Brep: reference/compas_brep.brep.md
          - BrepVertex: reference/compas_brep.vertex.md
          - BrepEdge: reference/compas_brep.edge.md
          - BrepLoop: reference/compas_brep.loop.md
          - BrepFace: reference/compas_brep.face.md
          - BrepTrim: reference/compas_brep.trim.md
      - Geometry:
          - NurbsCurve: reference/compas_brep.curves.nurbs.md
          - NurbsSurface: reference/compas_brep.surfaces.nurbs.md
      - Operations: reference/compas_brep.operations.md
      - Scene: reference/compas_brep.scene.md
      - Backends:
          - OCC: reference/compas_brep.backend.occ.md
          - Rhino: reference/compas_brep.backend.rhino.md
  - Other:
      - changelog.md
      - license.md
