name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    if: "!contains(github.event.pull_request.labels.*.name, 'docs-only')"
    runs-on: ubuntu-latest

    steps:
      - uses: compas-dev/compas-actions.build@v5.1.0
        with:
          python: "3.13"
          management_tool: uv
          invoke_lint: true
          invoke_test: true
          extras: "occ,dev"